# PROBLEM STATEMENT -1 :-

Go through www.nseindia.com and derive the following data about the input stock-list.

Data required: Open, High, Low, Close, Volume, Delivery Data, Delivery Percentage
Input stock-list: RELIANCE, HDFCBANK, ADANIPORTS, ITC, SBI, IOC, RBLBANK, SBI

Use necessary libraries to present the data obtained in a user-readable format.
The code must include one function which takes the stock as input and return the data required in the user-readable format.

Sample function definition-
def func(stocknames): # here stocknames is the list of input stocks
		< write code here >
	return data_required

# APPROACH :-

I have imported NSE from python library called nsetools which provides realtime data from nse website ,and then created empty list after this defined function which take argument as stock name then provides data required .

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import urllib.request
%matplotlib inline
from urllib.request import urlopen
from bs4 import BeautifulSoup
from nsetools import Nse
from pandas import DataFrame
nse = Nse()

DataRequired = []

def requiredData(code):

    quote = nse.get_quote(code)
    # dictionary which store data fetches from nse

    DesiredData= {}
    # empty dictionary

   # copied required data from quote
    DesiredData['Name'] = code
    DesiredData['Open'] = quote['basePrice']
    DesiredData['High'] = quote['dayHigh']
    DesiredData['Low'] = quote['dayLow']
    DesiredData['Close'] = quote['closePrice']
    DesiredData['Volume'] = quote['quantityTraded']
    DesiredData['Delivery Data'] = quote['deliveryQuantity']
    DesiredData['Delivery Percentage'] = quote['deliveryToTradedQuantity']
    # appended dictionary to the list
    DataRequired.append(DesiredData)


requiredData('reliance')
requiredData('hdfcbank')
requiredData('adaniports')
requiredData('itc')
requiredData('sbin')
requiredData('ioc')
requiredData('rblbank')
# passing the argument to function

#print(DataRequired) 


df = pd.DataFrame(DataRequired)
df.head(10)

,Name,Open,High,Low,Close,Volume,Delivery Data,Delivery Percentage
0,reliance,1929.80,1966.25,1930.05,1954.90,9114939.0,3073957.0,33.72
1,hdfcbank,1440.85,1449.00,1425.50,1433.30,8573787.0,4902182.0,57.18
2,adaniports,411.55,426.00,412.00,423.80,9170159.0,2295655.0,25.03
3,itc,193.65,196.35,192.40,194.40,15893346.0,5543840.0,34.88
4,sbin,244.25,248.95,244.25,248.05,37003272.0,9607134.0,25.96
5,ioc,84.60,86.00,84.10,85.85,14386967.0,4050603.0,28.15
6,rblbank,223.80,227.80,220.10,225.70,12095583.0,1363814.0,11.28